### ISSUE TITLE
Some Requests

### ISSUE THREAD

**Issue by Lincoln-Hannah** [JuliaData/Strapping.jl#23]
I made some requests of other packages with no luck.
Mentioning here in case you guys are interested. 

[https://github.com/mauro3/Parameters.jl/issues/153](url)
[https://github.com/JuliaData/DataFramesMeta.jl/issues/361](url)

**Comment by quinnj** [comment]
The links appear to be broken

**Comment by quinnj** [comment]
It doesn't seem like there's anything actionable for the Strapping.jl package in those requests.
