### ISSUE TITLE
Strapping.jl with databases

### ISSUE THREAD

**Issue by bjrnfrdnnd** [JuliaData/Strapping.jl#5]
Hello,

How would you go about using this package with a database?
Is it possible to do sqlalchemy-like queries with objects that define fields?
like 
        t_orm: \<sqlalchemy ORM object that maps to a table on disk>
        ssn: \<sqlalchemy session>
        q: \<sqlalchemy Query> = ssn.query(t_orm.id).order_by(t_orm.id.desc()).limit(1)
        last_transaction_id_on_disk = q.scalar()
        ssn.commit()

Can Strapping do something like that? 
The idea being that one can construct complex queries using orm objects that already have defined column names and such.

**Comment by quinnj** [comment]
Yes, this is generally possible, though not quite as "magical" as sqlalchemy. Strapping.jl currently works with generic Tables.jl-comptable inputs. So any database package that supports fetching results as a table (which is all the packages I know of, MySQL.jl, SQLite.jl, LibPQ.jl, ODBC.jl, ClickHouse.jl, etc.) you can feed the resultset directly into `Strapping.construct(T, resultset)` and it can work to "serialize" `T` from the query resultset. For deserialization, `Strapping.deconstruct` currently _produces_ a Tables.jl-compatible row-iterator that you could send to a database or other Tables.jl-compatible sink function (like `SQLite.load`, or `MySQL.load`). Note that currently `Strapping.deconstruct` produces a flat, denormalized "table" of the input object(s). So it may not map directly to the ideal "fully normalized" database structure that would be expected. Let me know if you have any other specific questions
