### ISSUE TITLE
Unexpected behavior in example

### ISSUE THREAD

**Issue by jademackay** [JuliaData/Strapping.jl#8]
Having copy and pasted the example into a single file:
```
using StructTypes
using Strapping

struct TestResult
    id::Int
    values::Vector{Float64}
end
StructTypes.StructType(::Type{TestResult}) = StructTypes.Struct()
StructTypes.idproperty(::Type{TestResult}) = :id

tbl = (id=[1, 1, 1, 2, 2, 2], values=[3.14, 3.15, 3.16, 40.1, 0.01, 2.34])
testresult = Strapping.construct(Vector{TestResult}, tbl)

struct Experiment
    id::Int
    name::String
    testresults::TestResult
end
StructTypes.StructType(::Type{Experiment}) = StructTypes.Struct()
StructTypes.idproperty(::Type{Experiment}) = :id

StructTypes.fieldprefix(::Type{Experiment}, nm::Symbol) = nm == :testresults ? :testresults_ : :_

tbl2 = (id=[1, 1, 1], name=["exp1", "exp1", "exp1"], testresults_id=[1, 1, 1], testresults_values=[3.14, 3.15, 3.16])
experiment = Strapping.construct(Experiment, tbl2)
```
I get the following:
```
@show experiment
experiment = Experiment(1, "exp1", TestResult(1, [3.14]))
```
I was expecting:
```
experiment = Experiment(1, "exp1", TestResult(1, [3.14, 3.15, 3.16]))
```
Have I misunderstood the example?

**Comment by quinnj** [comment]
Hmmm, that indeed seems wrong. Let me take a look.

**Comment by jademackay** [comment]
Thanks! Let me know if I can assist.

**Comment by quinnj** [comment]
Ok, this was a doozy of a refactor/rewrite, but I think I've got it all working: https://github.com/JuliaData/Strapping.jl/pull/10.

**Comment by jademackay** [comment]
Yes the fixes the example!
... however, in the meantime (using `main`  35c2c485 - with a tiny tweak) I had prepared the following:
```
using Tables
using StructTypes
using Strapping

## Type
Payload = NamedTuple
struct Service
    id::String
    data::Payload
end
StructTypes.StructType(::Type{Service}) = StructTypes.Struct()
StructTypes.idproperty(::Type{Service}) = :id

# implement Tables interface
Tables.istable(::Type{Service}) = true
Tables.rowaccess(::Type{Service}) = true
Tables.rows(x::Type{Service}) = x

import Tables: getcolumn, columnnames

function Tables.getcolumn(row::Service,i::Int)
    if i == 1
        return getfield(row,1)
    else
        return row.data[i-1]
    end
end

function Tables.getcolumn(row::Service,nm::Symbol)
    if nm == :id
        return row.id
    else
        return getproperty(row.data,nm)
    end
end

function Tables.columnnames(row::Service)
    vcat(:id,keys(row.data)...)
end


## Test

x = Service("qux",(a=1,b=3))
xd = Strapping.deconstruct(x)
xc = Strapping.construct(Service,xd)

x2 = Service("foo",(a=1,b=3))
X = [x,x2]
Xd = Strapping.deconstruct(X)
Xc = Strapping.construct(Vector{Service},Xd)
```
and  gratefully recovered the expected results `xc` and `Xc`.
On `jq/const` I get the error:
```
StructTypes.DictType() NamedTuple not allowed as aggregate field when calling Strapping.construct
```
I have yet to look at your changes ...

**Comment by quinnj** [comment]
Thanks for following up @jademackay; I have an idea on how we can allow that; let me see if I can put up another PR real quick (I'm currently switching laptops, so hoping setup goes smoothly)

**Comment by quinnj** [comment]
Alright, PR up: https://github.com/JuliaData/Strapping.jl/pull/11.

**Comment by jademackay** [comment]
@quinnj  Whoa! That's really great!
Also, thanks for creating Tables.jl Strapping.jl,  StructTypes.jl, and JSON3.jl . :-D

**Comment by jademackay** [comment]
I just remembered one more thing. TO get correct `Strapping.construct` behavior I needed to strip the field prefix from as follows:
```
diff --git a/src/Strapping.jl b/src/Strapping.jl
index 9138383..d11e1ec 100644
--- a/src/Strapping.jl
+++ b/src/Strapping.jl
@@ -255,7 +255,7 @@ function construct(::StructTypes.DictType, ::Type{T}, row, prefix, offset, i, nm
         nm = nms[j]
         val = construct(StructTypes.StructType(V), V, row, prefix, offset, j, nm; kw...)
         if K === Symbol
-            x[nm] = val
+            x[Symbol(replace(String(nm), String(prefix) => ""))] = val
         else
             x[StructTypes.construct(K, String(nm))] = val
         end
'''

**Comment by quinnj** [comment]
So you'll notice in the PR that I defined:
```julia
StructTypes.fieldprefix(::Type{Service}, nm::Symbol) = Symbol()
```
which overrides the default of having a `prefix` for struct fields, and therefore gives the same behavior you're expecting. Does that make sense?

**Comment by jademackay** [comment]
Oh I missed that - yes that makes sense.
Incidentally, and at the risk of really stretching this issue too far, I noticed that duplicate elements are de-duplicated by `Strapping.construct` *only if* they are consecutive:
```
julia> X = [x,x,x2];

julia> Xd = Strapping.deconstruct(X);

julia> Xc = Strapping.construct(Vector{Service},Xd) # de-duped
2-element Array{Service,1}:
 Service("qux", (a = 1, b = 3))
 Service("foo", (a = 1, b = 3))

julia> X = [x2,x,x];

julia> Xd = Strapping.deconstruct(X);

julia> Xc = Strapping.construct(Vector{Service},Xd) # de-duped
2-element Array{Service,1}:
 Service("foo", (a = 1, b = 3))
 Service("qux", (a = 1, b = 3))

julia> X = [x,x2,x];

julia> Xd = Strapping.deconstruct(X);

julia> Xc = Strapping.construct(Vector{Service},Xd) # NOT de-duped
3-element Array{Service,1}:
 Service("qux", (a = 1, b = 3))
 Service("foo", (a = 1, b = 3))
 Service("qux", (a = 1, b = 3))
```
Looking at the code it is not immediately clear why this happens - it is not a problem for me .

**Comment by quinnj** [comment]
Yes, that's a current, probably undocumented, requirement: collection fields need to be consecutive in the input rows. I have been thinking about how we could rework the API to allow returning a Dict{id_field_type, T}, because sometimes it's useful to return your `T` objects in a Dict, keyed on the idproperty anyway, which would also allow relaxing the consecutive rows requirement. If you have any ideas, I'd be open to what makes sense.

**Comment by jademackay** [comment]
Cool. Yes, since I use dictionaries a lot a `Dict{id_field_type, T}` would be nice. I will keep this in mind in my upcoming work.
Thanks again for your work.
